### ISSUE TITLE
Can I use eureka for getting node labels?

### ISSUE THREAD

**Issue by raarts** [Logimethods/docker-eureka#2]
Hi, I have trouble understanding if eureka can be used for my use case. 

Suppose I run it as a service on all managers in a docker swarm, and put it on its own swarm internal network, can a random container at startup use `curl` to retrieve the labels of the docker node it is running on?

What curl command would do that for example? 

This would be highly valuable for setting up node ids for clustered services for example.

**Comment by laugimethods** [comment]
What kind of node's "label" are you looking for?
Did you had a look at the regular `{{.Node.ID}}` and `{{.Node.Hostname}}` keywords?

**Comment by raarts** [comment]
I don't know exactly what you mean. I am referring to the startup script of a container in a docker swarm. I this case the `{{.Node.ID}}` are not available as far as I know. 

On the other hand, I just tested this out:

`docker inspect 086bf857fef0 | jq '.[0].Config.Labels["com.docker.swarm.node.id"]'`

followed by:

`docker node inspect w0d4coriw6fxa9yqgu66zmq2a | jq .[0].Spec.Labels`

would give me the labels. I'm going to try this out when I have some time. Thanks.

**Comment by laugimethods** [comment]
`{{.Node.ID}}` is not available to the running container but can be provided through an environment variable.
Like in https://github.com/Logimethods/smart-meter/blob/master/docker-compose.yml#L173

**Comment by raarts** [comment]
Never seen this. Does this also work in a Docker stack deploy?

**Comment by laugimethods** [comment]
Should work: https://github.com/Logimethods/smart-meter/blob/master/docker-up.sh#L27

**Comment by raarts** [comment]
And amazingly: it does! Never seen this trick elsewhere, and I know people are searching for this.
Ah, I see this is added in 17.10. Alas, node labels are not included in the list. Maybe later: https://github.com/docker/swarmkit/issues/2227.

But maybe this opens possibilities to fix my problems. Thanks!!
